import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Loader2 } from "lucide-react";
import { jsPDF } from "jspdf";
import { toast } from "sonner";

interface SelectedColor {
  id: string;
  code: string;
  name?: string;
  hex: string;
  cmyk?: string;
  rgb?: string;
  ral?: string;
  type: "ada" | "paint";
}

interface ExportPdfDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedColors: SelectedColor[];
}

export function ExportPdfDialog({
  open,
  onOpenChange,
  selectedColors,
}: ExportPdfDialogProps) {
  const [projectName, setProjectName] = useState("");
  const [architectOffice, setArchitectOffice] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const generatePDF = async () => {
    if (!projectName.trim() || !architectOffice.trim()) {
      toast.error("Please fill in all fields");
      return;
    }

    if (selectedColors.length === 0) {
      toast.error("No colors selected");
      return;
    }

    setIsGenerating(true);

    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      let yPosition = margin;

      // Header
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("iSIGN Color Selection", margin, yPosition);
      yPosition += 10;

      // Project Details
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text(`Project: ${projectName}`, margin, yPosition);
      yPosition += 7;
      doc.text(`Architect Office: ${architectOffice}`, margin, yPosition);
      yPosition += 7;
      doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 10;

      // Line separator
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Colors section
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Selected Colors", margin, yPosition);
      yPosition += 10;

      // Color items
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");

      for (let i = 0; i < selectedColors.length; i++) {
        const color = selectedColors[i];

        // Check if we need a new page
        if (yPosition > pageHeight - 40) {
          doc.addPage();
          yPosition = margin;
        }

        // Color swatch (rectangle)
        doc.setFillColor(color.hex);
        doc.rect(margin, yPosition, 30, 20, "F");

        // Add border to swatch
        doc.setDrawColor(150, 150, 150);
        doc.rect(margin, yPosition, 30, 20, "S");

        // Color information
        const textX = margin + 35;
        let textY = yPosition + 5;

        doc.setFont("helvetica", "bold");
        doc.text(color.code, textX, textY);
        textY += 5;

        doc.setFont("helvetica", "normal");
        if (color.name) {
          doc.text(color.name, textX, textY);
          textY += 5;
        }

        doc.text(`HEX: ${color.hex}`, textX, textY);
        textY += 5;

        if (color.cmyk) {
          doc.text(`CMYK: ${color.cmyk}`, textX, textY);
          textY += 5;
        }

        if (color.rgb) {
          doc.text(`RGB: ${color.rgb}`, textX, textY);
          textY += 5;
        }

        if (color.ral) {
          doc.text(`RAL: ${color.ral}`, textX, textY);
        }

        yPosition += 30;
      }

      // Footer
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Page ${i} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
        doc.text(
          "Generated by iSIGN Color Selector",
          pageWidth - margin,
          pageHeight - 10,
          { align: "right" }
        );
      }

      // Save the PDF
      const fileName = `${projectName.replace(/[^a-z0-9]/gi, "_")}_colors.pdf`;
      doc.save(fileName);

      toast.success("PDF exported successfully!");
      onOpenChange(false);
      setProjectName("");
      setArchitectOffice("");
    } catch (error) {
      console.error("PDF generation error:", error);
      toast.error("Failed to generate PDF");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Export Color Selection</DialogTitle>
          <DialogDescription>
            Enter project details to generate a PDF with your selected colors.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="project-name">Project Name</Label>
            <Input
              id="project-name"
              placeholder="e.g., Downtown Office Building"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
            />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="architect-office">Architect Office</Label>
            <Input
              id="architect-office"
              placeholder="e.g., Smith & Associates Architecture"
              value={architectOffice}
              onChange={(e) => setArchitectOffice(e.target.value)}
            />
          </div>
          <div className="text-sm text-muted-foreground">
            {selectedColors.length} color{selectedColors.length !== 1 ? "s" : ""}{" "}
            selected
          </div>
        </div>
        <DialogFooter>
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isGenerating}
          >
            Cancel
          </Button>
          <Button onClick={generatePDF} disabled={isGenerating}>
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                Generating...
              </>
            ) : (
              "Export PDF"
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
