import { useState } from "react";
import { trpc } from "@/lib/trpc";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface SelectedColor {
  id: string;
  code: string;
  name?: string;
  hex: string;
  type: "ada" | "paint";
  cmyk?: string;
  rgb?: string;
  ral?: string;
}

interface RequestSampleDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  selectedColors: SelectedColor[];
}

export function RequestSampleDialog({
  open,
  onOpenChange,
  selectedColors,
}: RequestSampleDialogProps) {
  const [projectName, setProjectName] = useState("");
  const [architectName, setArchitectName] = useState("");
  const [address, setAddress] = useState("");
  const [phoneNumber, setPhoneNumber] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const sendEmailMutation = trpc.email.sendSampleRequest.useMutation();

  const handleSubmit = async () => {
    // Validation
    if (!projectName.trim()) {
      toast.error("Please enter a project name");
      return;
    }
    if (!architectName.trim()) {
      toast.error("Please enter an architect name");
      return;
    }
    if (!address.trim()) {
      toast.error("Please enter an address");
      return;
    }
    if (!phoneNumber.trim()) {
      toast.error("Please enter a phone number");
      return;
    }
    if (selectedColors.length === 0) {
      toast.error("Please select at least one color");
      return;
    }
    if (selectedColors.length > 5) {
      toast.error("Maximum 5 colors allowed");
      return;
    }

    setIsSubmitting(true);

    try {
      // Generate PDF
      const pdf = new jsPDF();
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      let yPosition = 20;

      // Header
      pdf.setFontSize(20);
      pdf.setFont("helvetica", "bold");
      pdf.text("Color Sample Request", pageWidth / 2, yPosition, {
        align: "center",
      });

      yPosition += 15;

      // Project Information Section
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text("Project Information", 20, yPosition);
      yPosition += 10;

      pdf.setFontSize(11);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Project Name: ${projectName}`, 20, yPosition);
      yPosition += 7;
      pdf.text(`Architect: ${architectName}`, 20, yPosition);
      yPosition += 7;
      pdf.text(`Address: ${address}`, 20, yPosition);
      yPosition += 7;
      pdf.text(`Phone: ${phoneNumber}`, 20, yPosition);
      yPosition += 15;

      // Selected Colors Section
      pdf.setFontSize(14);
      pdf.setFont("helvetica", "bold");
      pdf.text(
        `Selected Colors (${selectedColors.length})`,
        20,
        yPosition
      );
      yPosition += 10;

      // Draw each color with swatch and details
      for (let i = 0; i < selectedColors.length; i++) {
        const color = selectedColors[i];

        // Check if we need a new page
        if (yPosition > pageHeight - 60) {
          pdf.addPage();
          yPosition = 20;
        }

        // Draw color swatch (30x30 box)
        pdf.setFillColor(color.hex);
        pdf.rect(20, yPosition, 30, 30, "F");

        // Draw border around swatch
        pdf.setDrawColor(200, 200, 200);
        pdf.rect(20, yPosition, 30, 30, "S");

        // Color details
        pdf.setFontSize(12);
        pdf.setFont("helvetica", "bold");
        pdf.text(color.name || color.code, 55, yPosition + 7);

        pdf.setFontSize(10);
        pdf.setFont("helvetica", "normal");
        pdf.text(`Code: ${color.code}`, 55, yPosition + 14);
        pdf.text(`Hex: ${color.hex}`, 55, yPosition + 20);

        if (color.cmyk) {
          pdf.text(`CMYK: ${color.cmyk}`, 55, yPosition + 26);
        }

        // Second column for additional info
        if (color.rgb) {
          pdf.text(`RGB: ${color.rgb}`, 120, yPosition + 14);
        }
        if (color.ral) {
          pdf.text(`RAL: ${color.ral}`, 120, yPosition + 20);
        }

        yPosition += 40;
      }

      // Footer
      yPosition += 10;
      if (yPosition > pageHeight - 30) {
        pdf.addPage();
        yPosition = 20;
      }
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(100, 100, 100);
      pdf.text(
        "This sample request was generated by iSIGN Color Selector",
        pageWidth / 2,
        yPosition,
        { align: "center" }
      );
      pdf.text(
        `Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`,
        pageWidth / 2,
        yPosition + 5,
        { align: "center" }
      );

      // Convert PDF to blob and base64
      const pdfBlob = pdf.output("blob");
      const pdfBase64 = await blobToBase64(pdfBlob);

      // Download PDF locally first
      const downloadUrl = URL.createObjectURL(pdfBlob);
      const link = document.createElement("a");
      link.href = downloadUrl;
      link.download = `color-sample-request-${projectName.replace(/\s+/g, "-").toLowerCase()}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(downloadUrl);

      // Send email via backend API
      try {
        await sendEmailMutation.mutateAsync({
          projectName,
          architectName,
          address,
          phoneNumber,
          colors: selectedColors.map(c => ({
            code: c.code,
            name: c.name,
            hex: c.hex,
            cmyk: c.cmyk,
            rgb: c.rgb,
            ral: c.ral,
          })),
          pdfBase64,
        });

        toast.success(
          "Sample request submitted successfully! PDF downloaded and email sent to submittal@isigninc.com"
        );
      } catch (emailError) {
        console.error("Email send error:", emailError);
        toast.warning(
          "PDF downloaded successfully, but email could not be sent. Please contact support."
        );
      }

      // Reset form
      setProjectName("");
      setArchitectName("");
      setAddress("");
      setPhoneNumber("");
      onOpenChange(false);
    } catch (error) {
      console.error("Error generating sample request:", error);
      toast.error("Failed to generate sample request. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  };

  const blobToBase64 = (blob: Blob): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = (reader.result as string).split(",")[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Request Color Samples</DialogTitle>
          <DialogDescription>
            Enter your project details to request physical color samples. Maximum
            5 colors per request.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="projectName">Project Name *</Label>
            <Input
              id="projectName"
              placeholder="e.g., Downtown Office Building"
              value={projectName}
              onChange={(e) => setProjectName(e.target.value)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="architectName">Architect Name *</Label>
            <Input
              id="architectName"
              placeholder="e.g., John Smith"
              value={architectName}
              onChange={(e) => setArchitectName(e.target.value)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="address">Address *</Label>
            <Input
              id="address"
              placeholder="e.g., 123 Main Street, City, State, ZIP"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="phoneNumber">Phone Number *</Label>
            <Input
              id="phoneNumber"
              placeholder="e.g., (555) 123-4567"
              value={phoneNumber}
              onChange={(e) => setPhoneNumber(e.target.value)}
            />
          </div>

          <div className="pt-2">
            <p className="text-sm text-muted-foreground">
              {selectedColors.length} of 5 colors selected
            </p>
            {selectedColors.length > 5 && (
              <p className="text-sm text-destructive mt-1">
                Please remove {selectedColors.length - 5} color(s) to continue
              </p>
            )}
          </div>
        </div>

        <div className="flex justify-end gap-2">
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={isSubmitting}
          >
            Cancel
          </Button>
          <Button onClick={handleSubmit} disabled={isSubmitting}>
            {isSubmitting ? "Processing..." : "Submit Request"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
